// <auto-generated />
using System;
using Hospital.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.Database.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240618174650_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ExameLaudo", b =>
                {
                    b.Property<Guid>("ExamesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LaudosId")
                        .HasColumnType("TEXT");

                    b.HasKey("ExamesId", "LaudosId");

                    b.HasIndex("LaudosId");

                    b.ToTable("ExameLaudo");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ConsultaAgendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoAtraso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("AgendamentosConsultas");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ExameAgendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoAtraso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("AgendamentosExames");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.RetornoAgendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoAtraso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("AgendamentosRetornos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Exame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("Exames");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Retorno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("Retornos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Telefone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Genero");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Convenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .HasColumnType("TEXT");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrição")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CNPJ");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Laudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("DocPath")
                        .IsUnique();

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Laudos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Medicamentos.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoDeBarras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Composicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipioAtivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDeBarras")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Medicamentos.MedicamentoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFabricacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("Status");

                    b.ToTable("MedicamentoLotes");
                });

            modelBuilder.Entity("LaudoMedicamento", b =>
                {
                    b.Property<Guid>("LaudosId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicamentosId")
                        .HasColumnType("TEXT");

                    b.HasKey("LaudosId", "MedicamentosId");

                    b.HasIndex("MedicamentosId");

                    b.ToTable("LaudoMedicamento");
                });

            modelBuilder.Entity("MedicamentoPaciente", b =>
                {
                    b.Property<Guid>("MedicamentosId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacientesId")
                        .HasColumnType("TEXT");

                    b.HasKey("MedicamentosId", "PacientesId");

                    b.HasIndex("PacientesId");

                    b.ToTable("MedicamentoPaciente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Admin", b =>
                {
                    b.HasBaseType("Hospital.Domain.Entities.Cadastros.Cadastro");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Medico", b =>
                {
                    b.HasBaseType("Hospital.Domain.Entities.Cadastros.Cadastro");

                    b.Property<int>("CRM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRMUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocCRMPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.HasIndex("DocCRMPath")
                        .IsUnique();

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Paciente", b =>
                {
                    b.HasBaseType("Hospital.Domain.Entities.Cadastros.Cadastro");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocConvenioPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocIDPath")
                        .HasColumnType("TEXT");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("DocConvenioPath")
                        .IsUnique();

                    b.HasIndex("DocIDPath")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ExameLaudo", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Exame", null)
                        .WithMany()
                        .HasForeignKey("ExamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Laudo", null)
                        .WithMany()
                        .HasForeignKey("LaudosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ConsultaAgendamento", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("AgendamentosConsultas")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("AgendamentosConsultas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("AgendamentosConsultas")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ExameAgendamento", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Consulta", "Consulta")
                        .WithMany("AgendamentosExames")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("AgendamentosExames")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("AgendamentosExames")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("AgendamentosExames")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Consulta");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.RetornoAgendamento", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("AgendamentosRetornos")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("AgendamentosRetornos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("AgendamentosRetornos")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Consulta");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Consulta", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Agendamentos.ConsultaAgendamento", "Agendamento")
                        .WithOne("Consulta")
                        .HasForeignKey("Hospital.Domain.Entities.Atendimentos.Consulta", "AgendamentoId");

                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("Consultas")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Agendamento");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Exame", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Agendamentos.ExameAgendamento", "Agendamento")
                        .WithOne("Exame")
                        .HasForeignKey("Hospital.Domain.Entities.Atendimentos.Exame", "AgendamentoId");

                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Consulta", "Consulta")
                        .WithMany("Exames")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("Exames")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("Exames")
                        .HasForeignKey("MedicoId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("Exames")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Agendamento");

                    b.Navigation("Consulta");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Retorno", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Agendamentos.RetornoAgendamento", "Agendamento")
                        .WithOne("Retorno")
                        .HasForeignKey("Hospital.Domain.Entities.Atendimentos.Retorno", "AgendamentoId");

                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Consulta", "Consulta")
                        .WithMany("Retornos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("Retornos")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("Retornos")
                        .HasForeignKey("MedicoId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("Retornos")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Agendamento");

                    b.Navigation("Consulta");

                    b.Navigation("Convenio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Laudo", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Atendimentos.Consulta", "Consulta")
                        .WithMany("Laudos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Medico", "Medico")
                        .WithMany("Laudos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", "Paciente")
                        .WithMany("Laudos")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Consulta");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Medicamentos.MedicamentoLote", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Medicamentos.Medicamento", "Medicamento")
                        .WithMany("MedicamentoLotes")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("LaudoMedicamento", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Laudo", null)
                        .WithMany()
                        .HasForeignKey("LaudosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Medicamentos.Medicamento", null)
                        .WithMany()
                        .HasForeignKey("MedicamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicamentoPaciente", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Medicamentos.Medicamento", null)
                        .WithMany()
                        .HasForeignKey("MedicamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Admin", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithOne()
                        .HasForeignKey("Hospital.Domain.Entities.Cadastros.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Medico", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithOne()
                        .HasForeignKey("Hospital.Domain.Entities.Cadastros.Medico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Paciente", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Convenio", "Convenio")
                        .WithMany("Pacientes")
                        .HasForeignKey("ConvenioId");

                    b.HasOne("Hospital.Domain.Entities.Cadastros.Cadastro", null)
                        .WithOne()
                        .HasForeignKey("Hospital.Domain.Entities.Cadastros.Paciente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ConsultaAgendamento", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.ExameAgendamento", b =>
                {
                    b.Navigation("Exame");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Agendamentos.RetornoAgendamento", b =>
                {
                    b.Navigation("Retorno");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Atendimentos.Consulta", b =>
                {
                    b.Navigation("AgendamentosExames");

                    b.Navigation("Exames");

                    b.Navigation("Laudos");

                    b.Navigation("Retornos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Convenio", b =>
                {
                    b.Navigation("AgendamentosConsultas");

                    b.Navigation("AgendamentosExames");

                    b.Navigation("AgendamentosRetornos");

                    b.Navigation("Consultas");

                    b.Navigation("Exames");

                    b.Navigation("Pacientes");

                    b.Navigation("Retornos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Medicamentos.Medicamento", b =>
                {
                    b.Navigation("MedicamentoLotes");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Medico", b =>
                {
                    b.Navigation("AgendamentosConsultas");

                    b.Navigation("AgendamentosExames");

                    b.Navigation("AgendamentosRetornos");

                    b.Navigation("Consultas");

                    b.Navigation("Exames");

                    b.Navigation("Laudos");

                    b.Navigation("Retornos");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Cadastros.Paciente", b =>
                {
                    b.Navigation("AgendamentosConsultas");

                    b.Navigation("AgendamentosExames");

                    b.Navigation("AgendamentosRetornos");

                    b.Navigation("Consultas");

                    b.Navigation("Exames");

                    b.Navigation("Laudos");

                    b.Navigation("Retornos");
                });
#pragma warning restore 612, 618
        }
    }
}
